name: Flask CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-lint-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 mypy bandit pip-audit pytest

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

      - name: Run Flake8
        run: flake8 . --exclude=venv

      - name: Run mypy
        run: mypy .

      - name: Run pip-audit
        run: pip-audit

      - name: Run Pytest
        run: pytest
